name: thread
description: A simple Isolated Thread wrapped with a type-safe Event Emitter for easier asynchronous communication. Setup events for the thread to reply to, or compute tasks individually.
version: 0.0.3
homepage: https://github.com/DrafaKiller/Thread-dart

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  async_signal: ^0.0.1
  events_emitter: ^0.2.0
  uuid: ^3.0.6