name: thread
description: A simple Isolated Thread wrapped with a type-safe Event Emitter for easier asynchronous communication. Setup events for the thread to reply to, or compute tasks individually.
version: 0.1.2
homepage: https://github.com/DrafaKiller/Thread-dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  async_signal: ^0.0.3
  events_emitter: ^0.3.0
  uuid: ^3.0.6